### PR TITLE
upgrade brave on launch

### PR DESCRIPTION
**Pull request by hugobuddel**
The image has a static version of Brave, but Brave is updated often, like once a week.

Would this keep Brave up to date? In general, I only relaunch Brave when there is an update, so there is no drawback for me to turn this around and update Brave every time it is launched.

See option nr. 2 in #1.

### CODE REVIEW

**Comment by hugobuddel** [comment]
Or would this never work because you can't write anything on a running instance at all? (I was hoping it would sort-of have a transient read-write layer above the persistent read-only layer.)

**Comment by truatpasteurdotfr** [comment]
I am not sure that a root owned installation would allow a regular user to update the package... What google-chrome is doing in the post-installation phase is to add chrome repository and an entry to update it. I haven't looked into brave installation (in the rpm) scripts.

**Comment by truatpasteurdotfr** [comment]
the runscript is ran:
- inside the read-only container by default (unless ther are overlays, or a sandbox)
- as the regular user (which is not priviledged), and would not work even with `sudo` as singularity does not allow privilege escalation inside the container, unless you run it as root)

**Comment by hugobuddel** [comment]
Thanks for your explanation. It seems that my solution won't work. I need to get some more hands-on experience with Singularity to understand how overlays work etc.

I was hoping Singularity would allow privilege escalation in the container without running it as root. But apparently this is not possible. (I use [proot](https://proot-me.github.io/) for those things, but it isn't as polished as Singularity/docker/etc.)

I'll close this PR.

**Comment by truatpasteurdotfr** [comment]
possible fix: if you bind a writeable path to /opt/brave.com ; the runscript will upgrade the brave at startup, otherwise. it will run the embedded version.

**Comment by hugobuddel** [comment]
your version works nicely @truatpasteurdotfr ! thanks

**Pull request closed without merging**
